name: geo-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  # Core scientific python
  - numpy
  
  # Plotting
  - matplotlib
  - plotly
  - seaborn

  # Spatial packages
  - pysal
  - pyproj>=3.0
  - rasterstats
  - geopy
  - cartopy
  - descartes
  - contextily
  - rioxarray
  - folium
  - geojson
  - netcdf4
  - nc-time-axis
  - regionmask

  # Jupyter
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
