name: geo-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  # Core scientific python
  - numpy
  - pyqt
  - tqdm
  - kiwisolver
  
  # Plotting
  - matplotlib
  - plotly
  - seaborn

  # Spatial packages
  - pysal
  - pyproj>=3.0
  - rasterstats
  - geopy
  - cartopy
  - descartes
  - contextily
  - rioxarray
  - folium
  - geojson
  - scipy
  - netcdf4
  - nc-time-axis
  - regionmask

  # Natural language processing
  - nltk
  - textblob

  # Jupyter Environment
  - papermill
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nbclean
  - nbresuse
  
  # Autograding
  - matplotcheck>=0.1.3
  - nbgrader
