#!/bin/bash

SHA=`git rev-parse --short HEAD`


# Get current branch
current_branch="$(git name-rev --name-only HEAD)"
echo $current_branch

if [ "$current_branch" == "master" ]
then
  # Create a tag for that commit number to use for tracking but also update latest
  docker build -t lwasser/geo-python:$SHA .
  docker build -t lwasser/geo-python:latest .
else
  # Create a tag for that particular branch
  docker build -t lwasser/geo-python:$current_branch .
fi
